name: Continuous Integration
on: [push]                      # Will make the workflow run every time you push to any branch

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest      # Sets the build environment a machine with the latest Ubuntu installed
    steps:
      - uses: actions/checkout@v2

      - run: npm i
        working-directory: ./DotnetTemplate.Web
      - run: dotnet build
      - run: dotnet test
      - run: npm run build
        working-directory: ./DotnetTemplate.Web
      - run: npm run lint
        working-directory: ./DotnetTemplate.Web
      - run: npm t
        working-directory: ./DotnetTemplate.Web