name: Continuous Integration
on: [push]                      # Will make the workflow run every time you push to any branch

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest      # Sets the build environment a machine with the latest Ubuntu installed
    steps:
      - uses: actions/checkout@v2

      - run: npm i
        working-directory: ./DotnetTemplate.Web
      - run: dotnet build
      - run: dotnet test
      - run: npm run build
        working-directory: ./DotnetTemplate.Web
      - run: npm run lint
        working-directory: ./DotnetTemplate.Web
      - run: npm t
        working-directory: ./DotnetTemplate.Web

  # deploy:   
  #   name: Deploy
  #   runs-on: ubuntu-latest      # Sets the build environment a machine with the latest Ubuntu installed
  #   needs: build
  #   if: github.ref == 'refs/heads/main'
  #   steps:
  #     - name: Check out repo
  #       uses: actions/checkout@v2 
  #     - name: Login to DockerHub
  #       uses: docker/login-action@v1
  #       with:
  #         username: ${{ secrets.DOCKERHUB_USERNAME }}
  #         password: ${{ secrets.DOCKERHUB_TOKEN }}
  #     - name: Build and push
  #       id: docker_build
  #       uses: docker/build-push-action@v2
  #       with:
  #         context: .
  #         file: Dockerfile.app
  #         push: true
  #         tags: anderspfyl/dotnettemplate:latest,anderspfyl/dotnettemplate:${{ github.sha }}

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build, Push and Release a Docker container to Heroku. # Your custom step name
        uses: gonuit/heroku-docker-deploy@v1.3.2 # GitHub action name (leave it as it is).
        with:
          email: ${{ secrets.HEROKU_EMAIL }}
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
          dockerfile_directory: ./
          dockerfile_name: Dockerfile.app
          docker_options: "--target production"
          process_type: web
          
   

  
