name: Continuous Integration
on: [push]                      # Will make the workflow run every time you push to any branch

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest      # Sets the build environment a machine with the latest Ubuntu installed
    steps:
      - uses: actions/checkout@v2

      - run: npm i
        working-directory: ./DotnetTemplate.Web
      - run: dotnet build
      - run: dotnet test
      - run: npm run build
        working-directory: ./DotnetTemplate.Web
      - run: npm run lint
        working-directory: ./DotnetTemplate.Web
      - run: npm t
        working-directory: ./DotnetTemplate.Web

  deploy:   
    name: Deploy
    runs-on: ubuntu-latest      # Sets the build environment a machine with the latest Ubuntu installed
    needs: build
    steps:
      # - name: Set up Docker Buildx
        # uses: docker/setup-buildx-action@v1
      - name: Check out repo
        uses: actions/checkout@v2 
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile.app
          push: true
          tag_with_sha: true
          tags: 
            - anderspfyl/dotnettemplate:latest
            - anderspfyl/dotnettemplate:${{ GITHUB_SHA }}
